# Generated by Django 2.0.7 on 2018-07-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=250)),
                ('Product_Key', models.CharField(max_length=250)),
                ('Machine_ID', models.CharField(max_length=250)),
                ('Machine_Type', models.CharField(max_length=250)),
                ('Asset_Number', models.CharField(max_length=250)),
                ('User', models.CharField(max_length=250)),
                ('Purchase_Date', models.CharField(max_length=250)),
                ('Notes', models.CharField(max_length=250)),
            ],
        ),
    ]
