# Generated by Django 2.0.7 on 2018-07-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0002_others'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Others',
            new_name='Other',
        ),
    ]
